# Generated by Django 5.2 on 2025-04-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Resume', max_length=100)),
                ('file_url', models.URLField(help_text='Link to your resume (e.g., Google Drive, GitHub, etc.)', max_length=500)),
            ],
        ),
    ]
