# Generated by Django 5.2 on 2025-04-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Core Skills',
        ),
        migrations.RemoveField(
            model_name='about',
            name='What I Do',
        ),
        migrations.AddField(
            model_name='about',
            name='core_skills',
            field=models.TextField(blank=True, help_text='List your core skills and areas of expertise. Use markdown for formatting.', null=True, verbose_name='Core Skills'),
        ),
        migrations.AddField(
            model_name='about',
            name='what_i_do',
            field=models.TextField(blank=True, help_text='Describe what you do and your professionals background.', null=True, verbose_name='What I Do'),
        ),
    ]
