# Generated by Django 5.2 on 2025-04-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_about_core_skills_remove_about_what_i_do_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='what_i_do',
            field=models.TextField(blank=True, help_text='Describe what you do and your professionals background. Use markdown for formatting.', null=True, verbose_name='What I Do'),
        ),
    ]
